<?php // autotool_migration 20121210120958 このファイルは自動化ツールにより編集されました ?>
<?php require_once('ADFlib/global_reg_emu.inc.php'); ?>
<?php
//印刷依頼担当FISユーザID
$PRTREQ_FIS_USER = array("5507029","5550149","5510601");


/*================================================
--テストデータ
--insert into ninsyo.eesc_user(従業員ＮＯ,氏名＿漢字,メールアドレス,会社コード１,所属職制コード１)values('FIS0001','FISテストユーザ1','shinbori@adf.co.jp','FIS','FIS');
--insert into ninsyo.eesc_user(従業員ＮＯ,氏名＿漢字,メールアドレス,会社コード１,所属職制コード１)values('FIS0002','FISテストユーザ2','shinbori@adf.co.jp','FIS','FIS');
--insert into ninsyo.eesc_user(従業員ＮＯ,氏名＿漢字,メールアドレス,会社コード１,所属職制コード１)values('FIS0003','FISテストユーザ3','shinbori@adf.co.jp','FIS','FIS');
--insert into ninsyo.project_user(従業員ＮＯ,社員属性,会社コード)values('FIS0001','1','FIS');
--insert into ninsyo.project_user(従業員ＮＯ,社員属性,会社コード)values('FIS0002','1','FIS');
--insert into ninsyo.project_user(従業員ＮＯ,社員属性,会社コード)values('FIS0003','1','FIS');
================================================*/
?>
